### ISSUE TITLE
install spaceflow error

### ISSUE THREAD

**Issue by wy-cmd** [hongleir/SpaceFlow#1]
Hi, When I was installing the software, I encountered the following problem, what is the cause of it and what is the best suggestion to solve it.
`(spaceflow_env) [wangyu@node12 ~]$ pip install SpaceFlow
Collecting SpaceFlow
  Using cached SpaceFlow-1.0.1-py3-none-any.whl (8.0 kB)
Collecting gudhi
  Using cached gudhi-3.5.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.3 MB)
Collecting matplotlib
  Using cached matplotlib-3.5.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
Collecting scanpy
  Using cached scanpy-1.9.1-py3-none-any.whl (2.0 MB)
Collecting torch-sparse>=0.6.11
  Using cached torch_sparse-0.6.14.tar.gz (51 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-m427h8hq/torch-sparse_67f85692654940128cf0d7781c736aa7/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by hongleir** [comment]
Hi, Thanks for that information, and sorry for that issue, You can address that by installing Pytorch first. Simply, execute the following command: `pip install torch`. And then, install SpaceFlow by: `pip install SpaceFlow`. Let me know if you meet any errors. Thanks!

**Comment by wy-cmd** [comment]
Thank you very much for your reply, the problem has been solved.
