### ISSUE TITLE
Reprodunction problem for breast cancer G1 sample

### ISSUE THREAD

**Issue by thelingxichen** [hongleir/SpaceFlow#11]
Hi @hongleir ,

Thanks for the excellent work! I have downloaded the breast cancer G1 dataset, and run the code configuration provided in README tutorials.

```python
from SpaceFlow import SpaceFlow
from scanpy import sc

def run_spaceflow(adata, epochs=1000, wdr='./'):
    sf = SpaceFlow.SpaceFlow(adata=adata)
    sf.preprocessing_data(n_top_genes=3000)

    sf.train(spatial_regularization_strength=0.1, z_dim=50, lr=1e-3, epochs=epochs, max_patience=50, min_stop=100, random_seed=42, gpu=0, regularization_acceleration=True, edge_subset_sz=1000000)


    sf.segmentation(domain_label_save_filepath=wdr+"domains.tsv", n_neighbors=50, resolution=1.0)
    sf.plot_segmentation(segmentation_figure_save_filepath=wdr+"domain_segmentation.pdf", colormap="tab20", scatter_sz=1., rsz=4., csz=4., wspace=.4, hspace=.5, left=0.125, right=0.9, bottom=0.1, top=0.9)

    sf.pseudo_Spatiotemporal_Map(pSM_values_save_filepath=wdr+"pSM_values.tsv", n_neighbors=20, resolution=1.0)
    sf.plot_pSM(pSM_figure_save_filepath=wdr+"pseudo-Spatiotemporal-Map.pdf", colormap="roma", scatter_sz=1., rsz=4., csz=4., wspace=.4, hspace=.5, left=0.125, right=0.9, bottom=0.1, top=0.9)


    adata.obsm['SpatialFlow_embedding'] = sf.embedding
    adata.obs['SpatialFlow_domain'] = sf.domains.tolist()
    adata.obs['SpatialFlow_time'] = sf.pSM_values

run_spaceflow(adata, epochs=1000)
```

<img width="1043" alt="Screen Shot 2023-08-25 at 5 11 11 PM" src="https://github.com/hongleir/SpaceFlow/assets/5020011/4024b18d-5969-4d41-9e78-9f4260019cbd">

While I noticed that the inferred domain and pseudo time (above figures) are not consistent upon examining Figure 5b and Figure 5e (below figures). Could you please share the reproductive code for this dataset or the domain and pseudo time information used to plot Figure 5?

<img width="802" alt="Screen Shot 2023-08-25 at 5 11 49 PM" src="https://github.com/hongleir/SpaceFlow/assets/5020011/30d7bae9-0474-460b-b735-21ca42716586">

Many Thanks,
Lingxi

**Comment by hongleir** [comment]
@thelingxichen Could you leave a email so that I can share the code?

**Comment by thelingxichen** [comment]
Hi @hongleir, my email is chanlingxi@gmail.com, can you share the reproductive code for the breast cancer G1 sample, or the the domain and pseudo-time information used to plot Figure 5? Many thanks!

**Comment by thelingxichen** [comment]
hi @hongleir can you help me with this issue, thanks

**Comment by thelingxichen** [comment]
Problem solved.
