### ISSUE TITLE
an issue about "libcudart.so.11.0" when import SpaceFlow

### ISSUE THREAD

**Issue by linpei26** [hongleir/SpaceFlow#3]
Hi Honglei!

I am trying to install SpaceFlow but encounter some problems when I run "from SpaceFlow import SpaceFlow" after installation

> "OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory"

the full messages were provided below[1].
When installing SpaceFlow, I run these cmd:

> conda create -n spaceflow python=3.7
> conda activate spaceflow
> conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cpuonly -c pytorch
> pip install torch-sparse==0.6.13 -f https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html
> pip install SpaceFlow

the 4th line was based on some google search[2] in order to build torch-sparse

Could you please take a look and maybe provide some suggestions?
Thanks in advance!

Pei Lin

[1]
(spaceflow) linpei@ourserver:~$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import squidpy as sq

>>> 
>>> 
>>> 
>>> import scanpy as sc
>>> 
>>> from SpaceFlow import SpaceFlow

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/site-packages/SpaceFlow/SpaceFlow.py", line 15, in <module>
    from torch_geometric.nn import GCNConv, DeepGraphInfomax
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/mnt/extraids/OceanStor-0/linpei/anaconda3/envs/spaceflow/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)

[2] https://github.com/pyg-team/pytorch_geometric/issues/5015

**Comment by hongleir** [comment]
Hi Pei,

      The issue is caused by the insconsistency between the pytorch versions you specified, the pytorch you installed is pytorch==1.12.0, and the dependency for torch-sparse you specified is torch-1.10.0. This inconsistency will definitely cause errors.

    Plase 
      1). first remove your current enviorment `conda env remove --name myenv`. 
      2). **EXACTLY** follow the README file in https://github.com/hongleir/SpaceFlow. 

The followings are important to care about when install:
    1. Create enviorment by `conda create -n spaceflow_env python=3.7`
    2. Then `conda activate spaceflow_env`
    3. Install pytorch through [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/), by manually choose your enviorment and it will generate the corresponding command for you to install. 
    4. Then install SpaceFlow by `pip install SpaceFlow`
    5. Check if there is any error by importing SpaceFlow and squidpy package:

    import squidpy as sq
    import scanpy as sc
    from SpaceFlow import SpaceFlow

    6. If there is error,  try to install the required packages in requirements.txt by:

    pip install -r requirements.txt

    Let me know if the isssue is solved. Thanks!

**Comment by linpei26** [comment]
something like these worked for me.

> pip install torch-sparse==0.6.13 -f https://pytorch-geometric.com/whl/torch-1.12.1+cu116.html
> conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge
> pip install SpaceFlow


However, I found this err when import the package

> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)

some google suggested that this is may be related to some issues of memory usage.

I wish to know if you have any suggestion on this?
Thanks in advance!

**Comment by linpei26** [comment]
Some suggest that this may be due to mismatched versions of pytorch

https://stackoverflow.com/questions/72039582/terminate-called-after-throwing-an-instance-of-stdbad-alloc-from-importing-t

**Comment by linpei26** [comment]
On our server (ubuntu 18.04)
I create a conda env with python 3.8 and install pytorch 1.12.0 + cuda 11.6

> pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
> conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.6 -c pytorch -c conda-forge

then
> pip install SpaceFlow

With these setting I finally install SpaceFlow 1.0.4 successfully and now I am testing the mouse organogenesis ST data.

Thank you!
